# Generated by Django 5.1.4 on 2024-12-29 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('profile_path', models.CharField(blank=True, max_length=500, null=True)),
                ('known_for_department', models.CharField(blank=True, max_length=400, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('deathday', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=500, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=300, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=400, null=True)),
                ('roles', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('profile_path', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=400, null=True)),
                ('job', models.CharField(blank=True, max_length=400, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('deathday', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=300, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=400, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('known_for', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('logo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('origin_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500, null=True)),
                ('tagline', models.CharField(blank=True, max_length=500, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, default=list, null=True)),
                ('homepage', models.URLField(blank=True, max_length=500, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=500, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=500, null=True)),
                ('trailer_link', models.URLField(blank=True, max_length=500, null=True)),
                ('teaser_link', models.URLField(blank=True, max_length=500, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.JSONField(blank=True, null=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='movies', to='Users.castmodel')),
                ('crew', models.ManyToManyField(blank=True, related_name='movies', to='Users.crewmodel')),
                ('genres', models.ManyToManyField(related_name='movies', to='Users.genremodel')),
                ('keywords', models.ManyToManyField(blank=True, related_name='movies', to='Users.keywordmodel')),
                ('production', models.ManyToManyField(blank=True, related_name='movies', to='Users.productioncompanymodel')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.moviemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseDateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=400)),
                ('release_date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_dates', to='Users.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.moviemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='moviemodel',
            index=models.Index(fields=['release_date'], name='Users_movie_release_d161f1_idx'),
        ),
        migrations.AddIndex(
            model_name='moviemodel',
            index=models.Index(fields=['popularity'], name='Users_movie_popular_1b790e_idx'),
        ),
        migrations.AddIndex(
            model_name='moviemodel',
            index=models.Index(fields=['vote_average'], name='Users_movie_vote_av_aa1d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='releasedatemodel',
            index=models.Index(fields=['country', 'release_date'], name='Users_relea_country_21976e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='releasedatemodel',
            unique_together={('movie', 'country')},
        ),
    ]
