# Generated by Django 5.1.4 on 2025-01-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecastmodel',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='moviecastmodel',
            name='cast_id',
            field=models.IntegerField(null=True),
        ),
    ]
