# Generated by Django 5.1.4 on 2025-07-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_moviecastmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
