# Generated by Django 5.1.4 on 2025-07-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_userprofilemodel_avatar_userprofilemodel_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('still_path', models.URLField(blank=True, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='Users.seasonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TVShowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('last_air_date', models.DateField(blank=True, null=True)),
                ('number_of_seasons', models.PositiveIntegerField(default=1)),
                ('number_of_episodes', models.PositiveIntegerField(default=1)),
                ('poster_path', models.URLField(blank=True, null=True)),
                ('backdrop_path', models.URLField(blank=True, null=True)),
                ('popularity', models.FloatField(default=0)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('cast', models.ManyToManyField(related_name='tvshows_cast', to='Users.personmodel')),
                ('crew', models.ManyToManyField(related_name='tvshows_crew', to='Users.personmodel')),
                ('genres', models.ManyToManyField(related_name='tvshows', to='Users.genremodel')),
            ],
        ),
        migrations.AddField(
            model_name='seasonmodel',
            name='tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='Users.tvshowmodel'),
        ),
    ]
