# Generated by Django 5.1.4 on 2025-01-02 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_userprofile_userprofilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 2, 12, 53, 1, 44821, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='is_active',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='preferred_actors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='preferred_genres',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
