# Generated by Django 5.1.4 on 2025-07-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_userlistmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('poster', 'Poster'), ('backdrop', 'Backdrop'), ('trailer', 'Trailer'), ('teaser', 'Teaser'), ('image', 'Image')], max_length=20)),
                ('url', models.URLField()),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Users.moviemodel')),
                ('tv_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Users.tvshowmodel')),
            ],
        ),
    ]
