# Generated by Django 5.1.4 on 2025-01-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_feedbackmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='updated_at',
        ),
    ]
