# Generated by Django 5.1.4 on 2025-01-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_moviemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='is_active',
            field=models.DateTimeField(default=True),
        ),
    ]
