# Generated by Django 5.1.4 on 2025-01-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_moviemodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
