# Generated by Django 5.1.4 on 2025-01-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_moviemodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmodel',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crewmodel',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
