# Generated by Django 5.1.4 on 2025-01-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_castmodel_gender_alter_crewmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncompanymodel',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
