# Generated by Django 5.1.4 on 2025-01-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_productioncompanymodel_origin_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemodel',
            old_name='production',
            new_name='production_companies',
        ),
    ]
