# Generated by Django 5.1.4 on 2025-01-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_rename_production_moviemodel_production_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmodel',
            name='also_known_as',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='castmodel',
            name='known_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewmodel',
            name='Known_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewmodel',
            name='also_known_as',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
