# Generated by Django 5.1.4 on 2025-01-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_castmodel_also_known_as_castmodel_known_credits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crewmodel',
            old_name='Known_credits',
            new_name='known_credits',
        ),
    ]
