# Generated by Django 5.1.4 on 2025-01-13 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_rename_known_credits_crewmodel_known_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='feedback_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='is_helpful',
            field=models.BooleanField(default=False),
        ),
    ]
