# Generated by Django 5.1.4 on 2025-01-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_remove_feedbackmodel_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('profile_path', models.CharField(blank=True, max_length=500, null=True)),
                ('known_credits', models.IntegerField(blank=True, null=True)),
                ('also_known_as', models.JSONField(blank=True, default=list, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('deathday', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=500, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=400, null=True)),
                ('known_for_department', models.CharField(blank=True, max_length=400, null=True)),
                ('roles', models.JSONField(blank=True, default=list, null=True)),
                ('department', models.CharField(blank=True, max_length=400, null=True)),
                ('job', models.CharField(blank=True, max_length=400, null=True)),
                ('known_for', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='crew',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='movies', to='Users.personmodel'),
        ),
        migrations.DeleteModel(
            name='CastModel',
        ),
        migrations.DeleteModel(
            name='CrewModel',
        ),
    ]
